type User {
  id: String
  name: String
  cpf: String
  phone: String
}

type Query {
  getAllUsers: [User]
}

input UserInput {
  name: String
  cpf: String,
  phone: String
}

type Mutation {
  createUser(input: UserInput): User
}